version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/frontend
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    # 数据卷
    volumes:
      # 将这个卷挂载到容器的 /app/data 目录。 即使容器重启或删除，/app/data 目录中的数据也会被保留
      - backend-data:/app/data

networks:
  app-network:
    driver: bridge

volumes:
  backend-data: 